// <auto-generated />
namespace PicassoWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddPromocion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPromocion));
        
        string IMigrationMetadata.Id
        {
            get { return "201310212132596_AddPromocion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
