// <auto-generated />
namespace PicassoWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddSucursallon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSucursallon));
        
        string IMigrationMetadata.Id
        {
            get { return "201310211949110_AddSucursal.lon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
